### ISSUE TITLE
Missing rabbitmq access to rabbitmq webmanagement

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry-community/cf-services-contrib-release#146]
when using rabbitmq broker, it seems that the admin plugin to be configured in the  AMQP broker, and exposed on port 20001 in the broker warden container. However, it seem that this port is not exposed on rabbit_node host, preventing any access to the rabbit admin console.

**Comment by rkoster** [comment]
From looking at the could I would say the `admin_port` [should be exposed](https://github.com/cloudfoundry-community/cf-services-contrib-release/blob/master/src/services/ng/rabbit/lib/rabbit_service/rabbit_node.rb#L298). The `admin_port` [is mapped to the](https://github.com/cloudfoundry-community/cf-services-contrib-release/blob/master/src/services/ng/rabbit/lib/rabbit_service/rabbit_node.rb#L422) `service_admin_port` [which defaults to 20001](https://github.com/cloudfoundry-community/cf-services-contrib-release/blob/master/src/services/ng/rabbit/lib/rabbit_service/rabbit_node.rb#L47).

**Comment by poblin-orange** [comment]
OK, i didnt notice the rabbit_node admin port is exposed in VCAP_SERVICES, calculated from rabbit port + 10000. Thanks for your quick feedback
